### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kingisawesome** [hyperchessbot/hyperbot#12]
![567601CC-BB4F-4E40-9550-BC4B7445DEB3](https://user-images.githubusercontent.com/70557332/99607773-7346da80-2a47-11eb-8577-c8c914ee2ea6.jpeg)
This only happened ever since I updated my repo last night because hyperchessbotauthor said he fixed something with the syzygy databases

**Comment by TheYoBots** [comment]
I too have gotten such notifications after I update my repo. There usually is no problem when this occurs, but just to be on the safer side I suggest that you go to ‘deploy’ tab in your app and click on ‘deploy branch’ and watch the logs build until heroku is deployed. If heroku is deployed you have no issue at all.

**Comment by hyperbotauthor** [comment]
This kind of error occurs if you push a change when a build has already started. As there can be only one running build on a free account, this triggers an error message.

You can have a look at running bulds in the Activity tab. With container apps a build getting stuck and being shown to be in progress is in the cards. If the situation gets out of hand then you can shut down a build using Heroku CLI, but this is a desparate measure and usually things heal themself.
